In [1]:
import numpy as np 
from matplotlib import pyplot as plt 
import pyross

In [9]:
# get the population, area and coordinates of several cities 
# London, Cambridge, Manchester
total_populations = [8.9e6, 0.124e6, 0.511e6]
populations = np.array([[p/4, p*3/4] for p in total_populations])
areas = np.array([1572, 40.7, 115.6])
coordinates = np.array([[51.5074, 0.1278], [52.2053, 0.1218], [53.4808, 2.2426]])

In [10]:
b = 1
c = 1 
generator = pyross.contactMatrix.SpatialContactMatrix(b, c, populations, areas, coordinates)

In [11]:
C = np.array([[18., 9.], 
              [3., 12.]]) 
C_spatial = generator.spatial_contact_matrix(C)

In [12]:
# contact matrix for London 
print(np.array(C_spatial)[0, :, 0, :])

[[12.3300229   6.16501145]
 [ 2.05500382  8.22001526]]


In [13]:
# contact matrix for Cambridge 
print(np.array(C_spatial)[1, :, 1, :])

[[3.57061895 1.78530947]
 [0.59510316 2.38041263]]


In [14]:
# contact matrix for Manchester
print(np.array(C_spatial)[2, :, 2, :])

[[7.51649002 3.75824501]
 [1.25274834 5.01099335]]


In [15]:
# contact matrix between London and Cambridge 
print(np.array(C_spatial)[0, :, 1, :])

[[0.7831908 0.3915954]
 [0.1305318 0.5221272]]


In [17]:
# contact matrix between London and Manchester
print(np.array(C_spatial)[0, :, 2, :])

[[2.30675315 1.15337658]
 [0.38445886 1.53783544]]


## Check that the local spatial matrices sum to give the overall one 

We want $$ C_{ij} = (\sum_{\mu, \nu} C^{\mu \nu}_{ij} N^\mu_i)/N_i$$

In [22]:
np.sum(np.sum(populations[:, :, None, None]*C_spatial, axis=0), axis=1)/np.sum(populations, axis=0)

array([[18.,  3.],
       [ 9., 12.]])

This is indeed the overall contact matrix