In [1]:
import numpy as np 
from matplotlib import pyplot as plt 
import pyross

In [33]:
# make up three populations 
total_populations = [2e5, 1e5, 0.5e5]
populations = np.array([[p/4, p*3/4] for p in total_populations])
areas = np.array([1000, 800, 500])
densities = total_populations/areas
commutes = np.array([[[p1*0.01, p2*0.01]]*3 for (p1, p2) in populations])

In [19]:
b = 1
work_ratio = 1/3
generator = pyross.contactMatrix.SpatialContactMatrix(b, work_ratio, populations, areas, commutes)

In [34]:
C = np.array([[18., 9.], 
              [3., 12.]]) 

C_spatial = generator.spatial_contact_matrix(C)

In [27]:
# contact matrix for 0
print(np.array(C_spatial)[0, :, 0, :])

[[18.95209893  9.47604946]
 [ 3.15868315 12.63473262]]


In [28]:
# contact matrix for 1
print(np.array(C_spatial)[1, :, 1, :])

[[14.80514566  7.40257283]
 [ 2.46752428  9.8700971 ]]


In [29]:
# contact matrix for 2
print(np.array(C_spatial)[2, :, 2, :])

[[18.94894791  9.47447396]
 [ 3.15815799 12.63263194]]


In [30]:
# contact matrix between 0 and 1 
print(np.array(C_spatial)[0, :, 1, :])

[[0.08166627 0.04083313]
 [0.01361104 0.05444418]]


In [31]:
# contact matrix between 0 and 2
print(np.array(C_spatial)[0, :, 2, :])

[[0.07867531 0.03933765]
 [0.01311255 0.0524502 ]]


## Check that the local spatial matrices sum to give the overall one 

We want $$ C_{ij} = (\sum_{\mu, \nu} C^{\mu \nu}_{ij} N^\mu_i)/N_i$$

In [32]:
np.sum(np.sum(populations[:, :, None, None]*C_spatial, axis=0), axis=1)/np.sum(populations, axis=0)

array([[18.,  3.],
       [ 9., 12.]])

This is indeed the overall contact matrix